# Generated by Django 4.2.7 on 2023-11-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnteredImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_file', models.FileField(upload_to='enteredImages/')),
            ],
        ),
        migrations.CreateModel(
            name='FilteredImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_file', models.FileField(upload_to='filteredImages/')),
            ],
        ),
    ]
